export const RegistrationField = [
   "targetName",
    "clientName",
     "industries",
    "caseCode",
    "SVP Comments",
    "OVP Comments",
    "targetDescription",
    "targetUnknown",
    "latestStartDate",
    "expectedProjectName",
    "teamComments",
    "expectedStart",
    "note",
    "teamSize",
    "svp",
    "operatingPartner",
    "sellingPartner",   
    "othersInvolved",
    "requestedSM",
    "likelihood",
    "stageStatus",
    "clientCommitment",
    "sector",
    "workPhase",
    "location",
    "conflictedOffice",
    "allocatedOffice",
    "officeToBeStaffed",
    "caseComplexity",
    "additionalServicesName",
    "clientType",
    "isRetainer",
    "isMBPartner",
    "isOVPHelp",
    "isSVPHelp",


]as const
