export interface Case {
    caseCode: string,
    caseName: string,
    clientCode: string,
    clientName: string,
    oldCaseCode: string,
    caseTypeCode: string,
    caseType: string,
    managingOfficeCode: string,
    managingOfficeAbbreviation: string,
    managingOfficeName: string,
    billingOfficeCode: string,
    billingOfficeAbbreviation: string,
    billingOfficeName: string,
    startDate: any,
    endDate: any,
    primaryIndustry: string,
    primaryCapability: string,
    isPrivateEquity: boolean,
    caseAttributes: string,
    type: string,
    caseManagerCode: string,
    caseServedByRingfence: string,
    customGroup: string
}