export interface DealExpertTrain {
    dealExpertTrainUpEmployeeId:number,
    firstName: string,
    lastName: string,
    familiarName: string,
    employeeCode: string,
    searchableName: string,
    officeName:string,
    homeOfficeCode:number,
    officeAbbreviation: string,
    employeeStatusCode?: string,
    pegRole?: number,
    pegRoleName?: string,
    officeAbbrevation?: string,
    levelName?: string,
    gradeName?: string,
    title?: string,
    abbreviation:string,
    isRingfenceEmployee: boolean,
    customGroup?:string,
    statusCode: string,
    regionId?:number,
    isExternalEmployee:number,
}
