import { GridService } from "./grid-column.service";
import { GridValues } from './grid-constants';
import { GridColumn, ColumnType } from '../interfaces/models';
import { TestBed } from '@angular/core/testing';
import { HttpClientTestingModule } from "@angular/common/http/testing";

describe('Grid Column Service', () => {
  let gridService: GridService;

  // Mock Data
  let fakeColumns: GridColumn[];
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [GridService],
      imports: [HttpClientTestingModule]
    });
    gridService = TestBed.get(GridService);
    setMockData();
  });

  it('should create service', () => {
    expect(gridService).toBeTruthy();
  });

  it('should return coldDef', () => {
    let coldef = gridService.getDefaultColumnDefinition;
    expect(coldef).toBeTruthy();
    expect(coldef.sortable).toEqual(true);
    expect(coldef.filter).toEqual(true);
    expect(coldef.resizable).toEqual(true);
  });

  it('should return ColumnDefinitions', () => {
    let coldefinitions = gridService.getColumnDefinitions(fakeColumns);
    expect(coldefinitions).toBeTruthy();
    expect(coldefinitions.length).toBeGreaterThan(0);
  });


  let setMockData = () => {
    // set Mock columns
    fakeColumns = [
      {
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Target",
        "field": "tdn",
        "filter": "textFilterComponent",
        "type": "text",
        "order": 1,
        "sort": "asc",
        "isQuickFilter": true,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": true,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Target Owner/Parent Company",
        "field": "cr",
        "filter": "textFilterComponent",
        "type": "text",
        "order": 2,
        "sort": null,
        "isQuickFilter": true,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Client",
        "field": "cdn",
        "filter": "textFilterComponent",
        "type": "text",
        "order": 3,
        "sort": null,
        "isQuickFilter": true,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Type of Work",
        "field": "wtn",
        "filter": "agSetColumnFilter",
        "type": "text",
        "order": 4,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "OMP",
        "field": "iomp",
        "filter": null,
        "type": "check",
        "order": 5,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Submit Dt",
        "field": "lsd",
        "filter": "agDateColumnFilter",
        "type": "date",
        "order": 6,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Stage",
        "field": "sgTN",
        "filter": "agSetColumnFilter",
        "type": "text",
        "order": 7,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Commit Dt",
        "field": "cd",
        "filter": "agDateColumnFilter",
        "type": "date",
        "order": 8,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Status",
        "field": "stn",
        "filter": "agSetColumnFilter",
        "type": "text",
        "order": 9,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Status Updt",
        "field": "sd",
        "filter": "agDateColumnFilter",
        "type": "date",
        "order": 10,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Completed Dt",
        "field": "ceD",
        "filter": "agDateColumnFilter",
        "type": "date",
        "order": 11,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {
        
        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Notes",
        "field": "ln",
        "filter": "textFilterComponent",
        "type": "text",
        "order": 12,
        "sort": null,
        "isQuickFilter": true,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      },
      {

        "columnId": 0,
        "rowGroupIndex": 0,
        "headerName": "Tags",
        "field": "tags",
        "filter": "tagsFilterComponent",
        "type": "tag",
        "order": 13,
        "sort": null,
        "isQuickFilter": false,
        "maxWidth": 130,
        "filterParams": "",
        "isEditable": false,
        "isRowDrag": false,
        "isRowGroup": false,
        "splitChar": "",
        "cellEditor": "",
        "headerClass": "",
        "cellRenderer": "",
        "tooltipComponent": "",
        "hasMiniFilter": false,
        "isMasked": false,
        "isDefault": false,
        "isHide": false,
        "hide": false,
        "sortOrder": 0,
        "roleSortOrder": 0,
        "isFilterable": false,
        "isOppName": false,
        "oppSortOrder": 0,
        "includeAsOppName": false,
        "isDefaultOppName": false,
        "columnWidth":0,
        "delimiter":"",
        "isDropdownVisible":false
      }
    ]
  }
})
