import { GridColumn } from "../../shared/interfaces/models";
import { TestBed } from "@angular/core/testing";
import { GridValues } from "../../shared/grid-generator/grid-constants";
import { RegistrationGridService } from './registration-grid.service';
import { FilterFunctions } from '../../shared/grid-generator/filter-functions';
import { HttpClientTestingModule } from "@angular/common/http/testing";

describe('Registration Grid Column Service', () => {
    let gridService: RegistrationGridService;

    // Mock Data
    let fakeColumns: GridColumn[];
    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [RegistrationGridService],
            imports: [HttpClientTestingModule,]
        });
        gridService = TestBed.inject(RegistrationGridService);
        setMockData();
    });

    it('should create service', () => {
        expect(gridService).toBeTruthy();
    });

    it('should return coldDef', () => {
        let coldef = gridService.getDefaultColumnDefinition;
        expect(coldef).toBeTruthy();
        expect(coldef.sortable).toEqual(true);
        expect(coldef.filter).toEqual(true);
        expect(coldef.resizable).toEqual(true);
    });

    it('should return ColumnDefinitions', () => {
        let coldefinitions = gridService.getColumnDefinitions(fakeColumns);
        expect(coldefinitions).toBeTruthy();
        expect(coldefinitions.length).toBeGreaterThan(0);
    });

    it('should compare dates greater than ', () => {
        let midnightDate = new Date();
        let currentDate = new Date();
        currentDate.setDate(currentDate.getDate() + 30);
        currentDate.setFullYear(currentDate.getFullYear() + 30);
        currentDate.setHours(currentDate.getHours() + 23);
        currentDate.setMinutes(currentDate.getMinutes() + 59);
        currentDate.setMilliseconds(currentDate.getMilliseconds() + 59);
        midnightDate.setHours(0, 0, 0, 0);
        let comparatorValue = FilterFunctions.dateComparator(midnightDate, currentDate.toISOString());
        expect(comparatorValue).toEqual(1);
    });

    it('should compare dates less than', () => {
        let midnightDate = new Date();
        midnightDate.setHours(0, 0, 0, 0);
        let currentDate = new Date();
        currentDate.setDate(currentDate.getDate() - 30);
        currentDate.setFullYear(currentDate.getFullYear() - 30);
        currentDate.setHours(currentDate.getHours() - 25);
        currentDate.setMinutes(currentDate.getMinutes() - 61);
        currentDate.setMilliseconds(currentDate.getMilliseconds() - 61);
        let comparatorValue = FilterFunctions.dateComparator(midnightDate, currentDate.toISOString());
        expect(comparatorValue).toEqual(-1);
    });

    let setMockData = () => {
        // set Mock columns
        fakeColumns = [
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Target",
                "field": "tdn",
                "filter": "textFilterComponent",
                "type": "text",
                "order": 1,
                "sort": "asc",
                "isQuickFilter": true,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": true,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false
            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Target Owner",
                "field": "cr",
                "filter": "textFilterComponent123",
                "type": "text",
                "order": 2,
                "sort": null,
                "isQuickFilter": true,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false
            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Client",
                "field": "cdn",
                "filter": "textFilterComponent",
                "type": "text",
                "order": 3,
                "sort": null,
                "isQuickFilter": true,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false
            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Type of Work",
                "field": "wtn",
                "filter": "agSetColumnFilter",
                "type": "text",
                "order": 4,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false
                ,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false
            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "OMP",
                "field": "iomp",
                "filter": null,
                "type": "check",
                "order": 5,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Submit Dt",
                "field": "lsd",
                "filter": "agDateColumnFilter",
                "type": "date",
                "order": 6,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Stage",
                "field": "sgTN",
                "filter": "agSetColumnFilter",
                "type": "text",
                "order": 7,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Commit Dt",
                "field": "cd",
                "filter": "agDateColumnFilter",
                "type": "date",
                "order": 8,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Status",
                "field": "stn",
                "filter": "agSetColumnFilter",
                "type": "text",
                "order": 9,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Status Updt",
                "field": "sd",
                "filter": "agDateColumnFilter",
                "type": "date",
                "order": 10,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId": 0,
                "rowGroupIndex": 0,
                "headerName": "Completed Dt",
                "field": "ceD",
                "filter": "agDateColumnFilter",
                "type": "date",
                "order": 11,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId":0,
                "rowGroupIndex":0,
                "headerName": "Notes",
                "field": "ln",
                "filter": "textFilterComponent",
                "type": "text",
                "order": 12,
                "sort": null,
                "isQuickFilter": true,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId":0,
                "rowGroupIndex":0,
                "headerName": "Tags",
                "field": "tags",
                "filter": "tagsFilterComponent",
                "type": "tag",
                "order": 13,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 130,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            },
            {
                "columnId":0,
                "rowGroupIndex":0,
                "headerName": "Deal Region",
                "field": "drn",
                "filter": "agSetColumnFilter",
                "type": "text",
                "order": 6,
                "sort": null,
                "isQuickFilter": false,
                "maxWidth": 200,
                "filterParams": "",
                "isEditable": false,
                "isRowDrag": false,
                "isRowGroup": false,
                "splitChar": "",
                "cellEditor": "",
                "headerClass": "",
                "cellRenderer": "",
                "tooltipComponent": "",
                "hasMiniFilter": false,
                "isMasked": false,
                "isHide": false,
                "isDefault": false,
                "hide": false,
                "sortOrder": 0,
                "roleSortOrder": 0,
                "isFilterable": false,
                "isOppName": false,
                "oppSortOrder": 0,
                "includeAsOppName": false,
                "isDefaultOppName": false,
                "columnWidth":0,
                "delimiter":"",
                "isDropdownVisible":false

            }
        ]
    }
})